name: Build

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'

jobs:
  BuildISO:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: cxbe
    - name: Compile
      run: |
        cd cxbe
        make -j $(grep -c processor /proc/cpuinfo)
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build - Linux"
        files: |
          cxbe/bin/cxbe
          cxbe/bin/cexe
          cxbe/bin/cdxt
          cxbe/bin/readxbe
